// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace kyxsan.Migrations
{
    /// <inheritdoc />
    public partial class AddPerferredUidOnUser : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "PreferredUid",
                table: "users",
                type: "TEXT",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "PreferredUid",
                table: "users");
        }
    }
}
